language: python
python:
  - "2.7"
  - "3.5"

env:
  - DJANGO=django==1.8
  - DJANGO=django==1.9

install:
  - pip install -q $DJANGO --use-mirrors
  - pip install https://github.com/jorgebastida/django-app-test-runner/zipball/master

script:
  - app-test-runner dajaxice dajaxice

branches:
  only:
    - master

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=django==1.8
    - python: "2.7"
      env: DJANGO=django==1.9
    - python: "3.5"
      env: DJANGO=django==1.8
    - python: "3.5"
      env: DJANGO=django==1.9
